### ISSUE TITLE
update to bootstrap 3.0.0

### ISSUE THREAD

**Issue by ssteinker** [famelo/Bootstrap#4]
UAAAARRRR. some work to do.

**Comment by mneuhaus** [comment]
Done :)

TYPO3 4.5 : https://github.com/famelo/TYPO3/tree/typo3-4.5
TYPO3 6.1 : https://github.com/famelo/TYPO3/tree/master
Bootstrap : https://github.com/famelo/Bootstrap/tree/master
Wordpress : https://github.com/famelo/Wordpress/tree/master

**Comment by mneuhaus** [comment]
As a side note, i've updated give with branch support as well :)

```
give famelo/TYPO3-Site:typo3-4.5
```
